// Code generated by protoc-gen-go.
// source: rpc.proto
// DO NOT EDIT!

/*
Package rpc is a generated protocol buffer package.

It is generated from these files:
	rpc.proto

It has these top-level messages:
	BlockRPCData
	LocateRequest
	LocateResponse
*/
package rpc

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import structs "github.com/hexablock/blockring/structs"
import chord "github.com/ipkg/go-chord"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type BlockRPCData struct {
	ID       []byte            `protobuf:"bytes,1,opt,name=ID,json=iD,proto3" json:"ID,omitempty"`
	Block    *structs.Block    `protobuf:"bytes,2,opt,name=Block,json=block" json:"Block,omitempty"`
	Location *structs.Location `protobuf:"bytes,3,opt,name=Location,json=location" json:"Location,omitempty"`
}

func (m *BlockRPCData) Reset()                    { *m = BlockRPCData{} }
func (m *BlockRPCData) String() string            { return proto.CompactTextString(m) }
func (*BlockRPCData) ProtoMessage()               {}
func (*BlockRPCData) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *BlockRPCData) GetID() []byte {
	if m != nil {
		return m.ID
	}
	return nil
}

func (m *BlockRPCData) GetBlock() *structs.Block {
	if m != nil {
		return m.Block
	}
	return nil
}

func (m *BlockRPCData) GetLocation() *structs.Location {
	if m != nil {
		return m.Location
	}
	return nil
}

type LocateRequest struct {
	Key []byte `protobuf:"bytes,1,opt,name=Key,json=key,proto3" json:"Key,omitempty"`
	N   int32  `protobuf:"varint,2,opt,name=N,json=n" json:"N,omitempty"`
}

func (m *LocateRequest) Reset()                    { *m = LocateRequest{} }
func (m *LocateRequest) String() string            { return proto.CompactTextString(m) }
func (*LocateRequest) ProtoMessage()               {}
func (*LocateRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *LocateRequest) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

func (m *LocateRequest) GetN() int32 {
	if m != nil {
		return m.N
	}
	return 0
}

type LocateResponse struct {
	Predecessor *chord.Vnode        `protobuf:"bytes,1,opt,name=Predecessor,json=predecessor" json:"Predecessor,omitempty"`
	Successors  []*chord.Vnode      `protobuf:"bytes,2,rep,name=Successors,json=successors" json:"Successors,omitempty"`
	Locations   []*structs.Location `protobuf:"bytes,3,rep,name=Locations,json=locations" json:"Locations,omitempty"`
}

func (m *LocateResponse) Reset()                    { *m = LocateResponse{} }
func (m *LocateResponse) String() string            { return proto.CompactTextString(m) }
func (*LocateResponse) ProtoMessage()               {}
func (*LocateResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *LocateResponse) GetPredecessor() *chord.Vnode {
	if m != nil {
		return m.Predecessor
	}
	return nil
}

func (m *LocateResponse) GetSuccessors() []*chord.Vnode {
	if m != nil {
		return m.Successors
	}
	return nil
}

func (m *LocateResponse) GetLocations() []*structs.Location {
	if m != nil {
		return m.Locations
	}
	return nil
}

func init() {
	proto.RegisterType((*BlockRPCData)(nil), "rpc.BlockRPCData")
	proto.RegisterType((*LocateRequest)(nil), "rpc.LocateRequest")
	proto.RegisterType((*LocateResponse)(nil), "rpc.LocateResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for BlockRPC service

type BlockRPCClient interface {
	GetBlockRPC(ctx context.Context, in *BlockRPCData, opts ...grpc.CallOption) (*BlockRPCData, error)
	SetBlockRPC(ctx context.Context, in *BlockRPCData, opts ...grpc.CallOption) (*BlockRPCData, error)
	TransferBlockRPC(ctx context.Context, in *BlockRPCData, opts ...grpc.CallOption) (*BlockRPCData, error)
}

type blockRPCClient struct {
	cc *grpc.ClientConn
}

func NewBlockRPCClient(cc *grpc.ClientConn) BlockRPCClient {
	return &blockRPCClient{cc}
}

func (c *blockRPCClient) GetBlockRPC(ctx context.Context, in *BlockRPCData, opts ...grpc.CallOption) (*BlockRPCData, error) {
	out := new(BlockRPCData)
	err := grpc.Invoke(ctx, "/rpc.BlockRPC/GetBlockRPC", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *blockRPCClient) SetBlockRPC(ctx context.Context, in *BlockRPCData, opts ...grpc.CallOption) (*BlockRPCData, error) {
	out := new(BlockRPCData)
	err := grpc.Invoke(ctx, "/rpc.BlockRPC/SetBlockRPC", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *blockRPCClient) TransferBlockRPC(ctx context.Context, in *BlockRPCData, opts ...grpc.CallOption) (*BlockRPCData, error) {
	out := new(BlockRPCData)
	err := grpc.Invoke(ctx, "/rpc.BlockRPC/TransferBlockRPC", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for BlockRPC service

type BlockRPCServer interface {
	GetBlockRPC(context.Context, *BlockRPCData) (*BlockRPCData, error)
	SetBlockRPC(context.Context, *BlockRPCData) (*BlockRPCData, error)
	TransferBlockRPC(context.Context, *BlockRPCData) (*BlockRPCData, error)
}

func RegisterBlockRPCServer(s *grpc.Server, srv BlockRPCServer) {
	s.RegisterService(&_BlockRPC_serviceDesc, srv)
}

func _BlockRPC_GetBlockRPC_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BlockRPCData)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlockRPCServer).GetBlockRPC(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpc.BlockRPC/GetBlockRPC",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlockRPCServer).GetBlockRPC(ctx, req.(*BlockRPCData))
	}
	return interceptor(ctx, in, info, handler)
}

func _BlockRPC_SetBlockRPC_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BlockRPCData)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlockRPCServer).SetBlockRPC(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpc.BlockRPC/SetBlockRPC",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlockRPCServer).SetBlockRPC(ctx, req.(*BlockRPCData))
	}
	return interceptor(ctx, in, info, handler)
}

func _BlockRPC_TransferBlockRPC_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BlockRPCData)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlockRPCServer).TransferBlockRPC(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpc.BlockRPC/TransferBlockRPC",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlockRPCServer).TransferBlockRPC(ctx, req.(*BlockRPCData))
	}
	return interceptor(ctx, in, info, handler)
}

var _BlockRPC_serviceDesc = grpc.ServiceDesc{
	ServiceName: "rpc.BlockRPC",
	HandlerType: (*BlockRPCServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetBlockRPC",
			Handler:    _BlockRPC_GetBlockRPC_Handler,
		},
		{
			MethodName: "SetBlockRPC",
			Handler:    _BlockRPC_SetBlockRPC_Handler,
		},
		{
			MethodName: "TransferBlockRPC",
			Handler:    _BlockRPC_TransferBlockRPC_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "rpc.proto",
}

// Client API for LocateRPC service

type LocateRPCClient interface {
	LocateKeyRPC(ctx context.Context, in *LocateRequest, opts ...grpc.CallOption) (*LocateResponse, error)
	LocateHashRPC(ctx context.Context, in *LocateRequest, opts ...grpc.CallOption) (*LocateResponse, error)
	LocateReplicatedKeyRPC(ctx context.Context, in *LocateRequest, opts ...grpc.CallOption) (*LocateResponse, error)
	LocateReplicatedHashRPC(ctx context.Context, in *LocateRequest, opts ...grpc.CallOption) (*LocateResponse, error)
}

type locateRPCClient struct {
	cc *grpc.ClientConn
}

func NewLocateRPCClient(cc *grpc.ClientConn) LocateRPCClient {
	return &locateRPCClient{cc}
}

func (c *locateRPCClient) LocateKeyRPC(ctx context.Context, in *LocateRequest, opts ...grpc.CallOption) (*LocateResponse, error) {
	out := new(LocateResponse)
	err := grpc.Invoke(ctx, "/rpc.LocateRPC/LocateKeyRPC", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *locateRPCClient) LocateHashRPC(ctx context.Context, in *LocateRequest, opts ...grpc.CallOption) (*LocateResponse, error) {
	out := new(LocateResponse)
	err := grpc.Invoke(ctx, "/rpc.LocateRPC/LocateHashRPC", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *locateRPCClient) LocateReplicatedKeyRPC(ctx context.Context, in *LocateRequest, opts ...grpc.CallOption) (*LocateResponse, error) {
	out := new(LocateResponse)
	err := grpc.Invoke(ctx, "/rpc.LocateRPC/LocateReplicatedKeyRPC", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *locateRPCClient) LocateReplicatedHashRPC(ctx context.Context, in *LocateRequest, opts ...grpc.CallOption) (*LocateResponse, error) {
	out := new(LocateResponse)
	err := grpc.Invoke(ctx, "/rpc.LocateRPC/LocateReplicatedHashRPC", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for LocateRPC service

type LocateRPCServer interface {
	LocateKeyRPC(context.Context, *LocateRequest) (*LocateResponse, error)
	LocateHashRPC(context.Context, *LocateRequest) (*LocateResponse, error)
	LocateReplicatedKeyRPC(context.Context, *LocateRequest) (*LocateResponse, error)
	LocateReplicatedHashRPC(context.Context, *LocateRequest) (*LocateResponse, error)
}

func RegisterLocateRPCServer(s *grpc.Server, srv LocateRPCServer) {
	s.RegisterService(&_LocateRPC_serviceDesc, srv)
}

func _LocateRPC_LocateKeyRPC_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LocateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LocateRPCServer).LocateKeyRPC(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpc.LocateRPC/LocateKeyRPC",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LocateRPCServer).LocateKeyRPC(ctx, req.(*LocateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LocateRPC_LocateHashRPC_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LocateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LocateRPCServer).LocateHashRPC(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpc.LocateRPC/LocateHashRPC",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LocateRPCServer).LocateHashRPC(ctx, req.(*LocateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LocateRPC_LocateReplicatedKeyRPC_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LocateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LocateRPCServer).LocateReplicatedKeyRPC(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpc.LocateRPC/LocateReplicatedKeyRPC",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LocateRPCServer).LocateReplicatedKeyRPC(ctx, req.(*LocateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LocateRPC_LocateReplicatedHashRPC_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LocateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LocateRPCServer).LocateReplicatedHashRPC(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpc.LocateRPC/LocateReplicatedHashRPC",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LocateRPCServer).LocateReplicatedHashRPC(ctx, req.(*LocateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _LocateRPC_serviceDesc = grpc.ServiceDesc{
	ServiceName: "rpc.LocateRPC",
	HandlerType: (*LocateRPCServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "LocateKeyRPC",
			Handler:    _LocateRPC_LocateKeyRPC_Handler,
		},
		{
			MethodName: "LocateHashRPC",
			Handler:    _LocateRPC_LocateHashRPC_Handler,
		},
		{
			MethodName: "LocateReplicatedKeyRPC",
			Handler:    _LocateRPC_LocateReplicatedKeyRPC_Handler,
		},
		{
			MethodName: "LocateReplicatedHashRPC",
			Handler:    _LocateRPC_LocateReplicatedHashRPC_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "rpc.proto",
}

func init() { proto.RegisterFile("rpc.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 397 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x93, 0xc1, 0xce, 0x93, 0x40,
	0x10, 0xc7, 0x05, 0x52, 0xd3, 0x0e, 0xd8, 0xb4, 0x6b, 0xa2, 0x84, 0x53, 0x43, 0x3c, 0xf4, 0x60,
	0x21, 0x41, 0x3d, 0xe8, 0xd1, 0x92, 0xa8, 0xa9, 0x31, 0x0d, 0x35, 0xde, 0xe9, 0x32, 0x02, 0x69,
	0x65, 0x71, 0x77, 0x49, 0xec, 0x43, 0xf8, 0x0c, 0xbe, 0x84, 0x0f, 0x68, 0x58, 0xd8, 0xda, 0x7e,
	0xfd, 0x2e, 0x7c, 0x97, 0x76, 0x67, 0xe6, 0xff, 0xdb, 0xf9, 0xcf, 0x4e, 0x80, 0x09, 0xaf, 0x69,
	0x50, 0x73, 0x26, 0x19, 0xb1, 0x78, 0x4d, 0xbd, 0xd7, 0x79, 0x29, 0x8b, 0x66, 0x1f, 0x50, 0xf6,
	0x23, 0x2c, 0xf0, 0x57, 0xba, 0x3f, 0x32, 0x7a, 0x08, 0xd5, 0x2f, 0x2f, 0xab, 0x3c, 0x14, 0x92,
	0x37, 0x54, 0x0a, 0xfd, 0xdf, 0xa1, 0x9e, 0x7f, 0x41, 0x95, 0xf5, 0x21, 0x0f, 0x73, 0xb6, 0xa2,
	0x05, 0xe3, 0x59, 0x58, 0xa1, 0xec, 0x34, 0xbe, 0x00, 0xe7, 0x7d, 0x7b, 0x4d, 0xb2, 0x5d, 0xc7,
	0xa9, 0x4c, 0xc9, 0x14, 0xcc, 0x4f, 0xb1, 0x6b, 0x2c, 0x8c, 0xa5, 0x93, 0x98, 0x65, 0x4c, 0x5e,
	0xc0, 0x48, 0xd5, 0x5d, 0x73, 0x61, 0x2c, 0xed, 0x68, 0x1a, 0xe8, 0x16, 0x1d, 0x35, 0x52, 0x1e,
	0xc8, 0x0a, 0xc6, 0x9f, 0x19, 0x4d, 0x65, 0xc9, 0x2a, 0xd7, 0x52, 0xc2, 0xf9, 0x59, 0xa8, 0x0b,
	0xc9, 0xf8, 0xd8, 0x9f, 0xfc, 0x10, 0x9e, 0xa8, 0x2c, 0x26, 0xf8, 0xb3, 0x41, 0x21, 0xc9, 0x0c,
	0xac, 0x0d, 0x9e, 0xfa, 0xb6, 0xd6, 0x01, 0x4f, 0xc4, 0x01, 0xe3, 0x8b, 0xea, 0x39, 0x4a, 0x8c,
	0xca, 0xff, 0x63, 0xc0, 0x54, 0x13, 0xa2, 0x66, 0x95, 0x40, 0x12, 0x80, 0xbd, 0xe5, 0x98, 0x21,
	0x45, 0x21, 0x18, 0x57, 0xa8, 0x1d, 0x39, 0x81, 0x9a, 0x2f, 0xf8, 0x56, 0xb1, 0x0c, 0x13, 0xbb,
	0xfe, 0x2f, 0x20, 0x2f, 0x01, 0x76, 0x0d, 0xed, 0x02, 0xe1, 0x9a, 0x0b, 0xeb, 0x46, 0x0e, 0xe2,
	0x5c, 0x27, 0x21, 0x4c, 0xb4, 0x6f, 0xe1, 0x5a, 0x4a, 0x7c, 0xcf, 0x44, 0x13, 0x3d, 0x91, 0x88,
	0xfe, 0x1a, 0x30, 0xd6, 0x0f, 0x49, 0xde, 0x80, 0xfd, 0x01, 0xe5, 0x39, 0x9c, 0x07, 0xed, 0x3a,
	0x2f, 0x9f, 0xd9, 0xbb, 0x4d, 0xf9, 0x8f, 0x5a, 0x6c, 0xf7, 0x00, 0xec, 0x1d, 0xcc, 0xbe, 0xf2,
	0xb4, 0x12, 0xdf, 0x91, 0x0f, 0x65, 0xa3, 0xdf, 0x66, 0x3f, 0x28, 0xb6, 0xd4, 0x5b, 0x70, 0xba,
	0x60, 0x83, 0xa7, 0x36, 0x26, 0x0a, 0xb9, 0x5a, 0x95, 0xf7, 0xf4, 0x2a, 0xd7, 0x2d, 0x43, 0x99,
	0xe8, 0x57, 0xfa, 0x31, 0x15, 0xc5, 0x40, 0x76, 0x0d, 0xcf, 0x74, 0xae, 0x3e, 0x96, 0xed, 0x21,
	0x1b, 0x6e, 0x20, 0x86, 0xe7, 0x77, 0x2f, 0x19, 0x6e, 0x65, 0xff, 0x58, 0x7d, 0x15, 0xaf, 0xfe,
	0x05, 0x00, 0x00, 0xff, 0xff, 0xda, 0x95, 0xf4, 0x20, 0x81, 0x03, 0x00, 0x00,
}
