// Code generated by protoc-gen-go.
// source: structs.proto
// DO NOT EDIT!

/*
Package structs is a generated protocol buffer package.

It is generated from these files:
	structs.proto

It has these top-level messages:
	Block
	Location
	RequestOptions
*/
package structs

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import chord "github.com/ipkg/go-chord"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type BlockType int32

const (
	BlockType_ROOT     BlockType = 0
	BlockType_DATA     BlockType = 1
	BlockType_LOG      BlockType = 2
	BlockType_LOGENTRY BlockType = 3
)

var BlockType_name = map[int32]string{
	0: "ROOT",
	1: "DATA",
	2: "LOG",
	3: "LOGENTRY",
}
var BlockType_value = map[string]int32{
	"ROOT":     0,
	"DATA":     1,
	"LOG":      2,
	"LOGENTRY": 3,
}

func (x BlockType) String() string {
	return proto.EnumName(BlockType_name, int32(x))
}
func (BlockType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type Block struct {
	Type BlockType `protobuf:"varint,1,opt,name=Type,json=type,enum=structs.BlockType" json:"Type,omitempty"`
	Data []byte    `protobuf:"bytes,2,opt,name=Data,json=data,proto3" json:"Data,omitempty"`
}

func (m *Block) Reset()                    { *m = Block{} }
func (m *Block) String() string            { return proto.CompactTextString(m) }
func (*Block) ProtoMessage()               {}
func (*Block) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Block) GetType() BlockType {
	if m != nil {
		return m.Type
	}
	return BlockType_ROOT
}

func (m *Block) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type Location struct {
	Id       []byte       `protobuf:"bytes,1,opt,name=Id,json=id,proto3" json:"Id,omitempty"`
	Priority int32        `protobuf:"varint,2,opt,name=Priority,json=priority" json:"Priority,omitempty"`
	Vnode    *chord.Vnode `protobuf:"bytes,3,opt,name=Vnode,json=vnode" json:"Vnode,omitempty"`
}

func (m *Location) Reset()                    { *m = Location{} }
func (m *Location) String() string            { return proto.CompactTextString(m) }
func (*Location) ProtoMessage()               {}
func (*Location) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Location) GetId() []byte {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *Location) GetPriority() int32 {
	if m != nil {
		return m.Priority
	}
	return 0
}

func (m *Location) GetVnode() *chord.Vnode {
	if m != nil {
		return m.Vnode
	}
	return nil
}

type RequestOptions struct {
	PeerSetKey  []byte `protobuf:"bytes,1,opt,name=PeerSetKey,json=peerSetKey,proto3" json:"PeerSetKey,omitempty"`
	PeerSetSize int32  `protobuf:"varint,2,opt,name=PeerSetSize,json=peerSetSize" json:"PeerSetSize,omitempty"`
	Source      []byte `protobuf:"bytes,3,opt,name=Source,json=source,proto3" json:"Source,omitempty"`
	Destination []byte `protobuf:"bytes,4,opt,name=Destination,json=destination,proto3" json:"Destination,omitempty"`
}

func (m *RequestOptions) Reset()                    { *m = RequestOptions{} }
func (m *RequestOptions) String() string            { return proto.CompactTextString(m) }
func (*RequestOptions) ProtoMessage()               {}
func (*RequestOptions) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *RequestOptions) GetPeerSetKey() []byte {
	if m != nil {
		return m.PeerSetKey
	}
	return nil
}

func (m *RequestOptions) GetPeerSetSize() int32 {
	if m != nil {
		return m.PeerSetSize
	}
	return 0
}

func (m *RequestOptions) GetSource() []byte {
	if m != nil {
		return m.Source
	}
	return nil
}

func (m *RequestOptions) GetDestination() []byte {
	if m != nil {
		return m.Destination
	}
	return nil
}

func init() {
	proto.RegisterType((*Block)(nil), "structs.Block")
	proto.RegisterType((*Location)(nil), "structs.Location")
	proto.RegisterType((*RequestOptions)(nil), "structs.RequestOptions")
	proto.RegisterEnum("structs.BlockType", BlockType_name, BlockType_value)
}

func init() { proto.RegisterFile("structs.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 325 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x44, 0x90, 0x51, 0x4b, 0xfb, 0x30,
	0x14, 0xc5, 0xff, 0xed, 0xda, 0xad, 0xff, 0xdb, 0x3a, 0xca, 0x7d, 0x90, 0xb2, 0x07, 0x29, 0x7d,
	0x90, 0x21, 0xd8, 0xc1, 0x04, 0xdf, 0xa7, 0x93, 0x21, 0x0e, 0x3b, 0xb2, 0x22, 0xe8, 0x5b, 0xd7,
	0x86, 0x2d, 0x4c, 0x9b, 0x98, 0xa6, 0x42, 0xfd, 0x0c, 0x7e, 0x68, 0x69, 0x56, 0xb7, 0xa7, 0xe4,
	0x9c, 0x93, 0x7b, 0x7f, 0xb9, 0x17, 0xce, 0x2a, 0x25, 0xeb, 0x5c, 0x55, 0xb1, 0x90, 0x5c, 0x71,
	0x1c, 0x74, 0x72, 0x14, 0x6d, 0x99, 0xda, 0xd5, 0x9b, 0x38, 0xe7, 0x1f, 0x13, 0x26, 0xf6, 0xdb,
	0xc9, 0x96, 0x5f, 0xe7, 0x3b, 0x2e, 0x8b, 0x49, 0x49, 0xd5, 0xe1, 0x71, 0x74, 0x0f, 0xf6, 0xdd,
	0x3b, 0xcf, 0xf7, 0x78, 0x09, 0x56, 0xda, 0x08, 0x1a, 0x18, 0xa1, 0x31, 0x1e, 0x4e, 0x31, 0xfe,
	0xeb, 0xa9, 0xd3, 0x36, 0x21, 0x96, 0x6a, 0x04, 0x45, 0x04, 0x6b, 0x9e, 0xa9, 0x2c, 0x30, 0x43,
	0x63, 0xec, 0x11, 0xab, 0xc8, 0x54, 0x16, 0xbd, 0x81, 0xb3, 0xe4, 0x79, 0xa6, 0x18, 0x2f, 0x71,
	0x08, 0xe6, 0x63, 0xa1, 0xbb, 0x78, 0xc4, 0x64, 0x05, 0x8e, 0xc0, 0x59, 0x49, 0xc6, 0x25, 0x53,
	0x8d, 0xae, 0xb1, 0x89, 0x23, 0x3a, 0x8d, 0x11, 0xd8, 0x2f, 0x25, 0x2f, 0x68, 0xd0, 0x0b, 0x8d,
	0xb1, 0x3b, 0xf5, 0x62, 0xfd, 0xbb, 0x58, 0x7b, 0xc4, 0xfe, 0x6a, 0x8f, 0xe8, 0xc7, 0x80, 0x21,
	0xa1, 0x9f, 0x35, 0xad, 0x54, 0x22, 0x5a, 0x42, 0x85, 0x17, 0x00, 0x2b, 0x4a, 0xe5, 0x9a, 0xaa,
	0x27, 0xda, 0x74, 0x28, 0x10, 0x47, 0x07, 0x43, 0x70, 0xbb, 0x7c, 0xcd, 0xbe, 0x69, 0x47, 0x75,
	0xc5, 0xc9, 0xc2, 0x73, 0xe8, 0xaf, 0x79, 0x2d, 0xf3, 0x03, 0xd9, 0x23, 0xfd, 0x4a, 0xab, 0xb6,
	0x72, 0x4e, 0x2b, 0xc5, 0x4a, 0x3d, 0x4b, 0x60, 0xe9, 0xd0, 0x2d, 0x4e, 0xd6, 0xd5, 0x2d, 0xfc,
	0x3f, 0x6e, 0x04, 0x1d, 0xb0, 0x48, 0x92, 0xa4, 0xfe, 0xbf, 0xf6, 0x36, 0x9f, 0xa5, 0x33, 0xdf,
	0xc0, 0x01, 0xf4, 0x96, 0xc9, 0xc2, 0x37, 0xd1, 0x03, 0x67, 0x99, 0x2c, 0x1e, 0x9e, 0x53, 0xf2,
	0xea, 0xf7, 0x36, 0x7d, 0xbd, 0xee, 0x9b, 0xdf, 0x00, 0x00, 0x00, 0xff, 0xff, 0xf8, 0xd4, 0xd2,
	0x15, 0xac, 0x01, 0x00, 0x00,
}
