// Code generated by protoc-gen-go.
// source: structs.proto
// DO NOT EDIT!

/*
Package structs is a generated protocol buffer package.

It is generated from these files:
	structs.proto

It has these top-level messages:
	Block
	Location
	Reference
*/
package structs

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import chord "github.com/ipkg/go-chord"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type BlockType int32

const (
	BlockType_ROOTBLOCK     BlockType = 0
	BlockType_DATABLOCK     BlockType = 1
	BlockType_LOGBLOCK      BlockType = 2
	BlockType_LOGENTRYBLOCK BlockType = 3
)

var BlockType_name = map[int32]string{
	0: "ROOTBLOCK",
	1: "DATABLOCK",
	2: "LOGBLOCK",
	3: "LOGENTRYBLOCK",
}
var BlockType_value = map[string]int32{
	"ROOTBLOCK":     0,
	"DATABLOCK":     1,
	"LOGBLOCK":      2,
	"LOGENTRYBLOCK": 3,
}

func (x BlockType) String() string {
	return proto.EnumName(BlockType_name, int32(x))
}
func (BlockType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type Block struct {
	Type BlockType `protobuf:"varint,1,opt,name=Type,json=type,enum=structs.BlockType" json:"Type,omitempty"`
	Data []byte    `protobuf:"bytes,2,opt,name=Data,json=data,proto3" json:"Data,omitempty"`
}

func (m *Block) Reset()                    { *m = Block{} }
func (m *Block) String() string            { return proto.CompactTextString(m) }
func (*Block) ProtoMessage()               {}
func (*Block) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Block) GetType() BlockType {
	if m != nil {
		return m.Type
	}
	return BlockType_ROOTBLOCK
}

func (m *Block) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type Location struct {
	Id       []byte       `protobuf:"bytes,1,opt,name=Id,json=id,proto3" json:"Id,omitempty"`
	Priority int32        `protobuf:"varint,2,opt,name=Priority,json=priority" json:"Priority,omitempty"`
	Vnode    *chord.Vnode `protobuf:"bytes,3,opt,name=Vnode,json=vnode" json:"Vnode,omitempty"`
}

func (m *Location) Reset()                    { *m = Location{} }
func (m *Location) String() string            { return proto.CompactTextString(m) }
func (*Location) ProtoMessage()               {}
func (*Location) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Location) GetId() []byte {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *Location) GetPriority() int32 {
	if m != nil {
		return m.Priority
	}
	return 0
}

func (m *Location) GetVnode() *chord.Vnode {
	if m != nil {
		return m.Vnode
	}
	return nil
}

type Reference struct {
	Previous []byte `protobuf:"bytes,1,opt,name=Previous,json=previous,proto3" json:"Previous,omitempty"`
	Data     []byte `protobuf:"bytes,2,opt,name=Data,json=data,proto3" json:"Data,omitempty"`
	Mode     uint32 `protobuf:"varint,3,opt,name=Mode,json=mode" json:"Mode,omitempty"`
	Name     string `protobuf:"bytes,4,opt,name=Name,json=name" json:"Name,omitempty"`
	Inline   []byte `protobuf:"bytes,5,opt,name=Inline,json=inline,proto3" json:"Inline,omitempty"`
}

func (m *Reference) Reset()                    { *m = Reference{} }
func (m *Reference) String() string            { return proto.CompactTextString(m) }
func (*Reference) ProtoMessage()               {}
func (*Reference) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Reference) GetPrevious() []byte {
	if m != nil {
		return m.Previous
	}
	return nil
}

func (m *Reference) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *Reference) GetMode() uint32 {
	if m != nil {
		return m.Mode
	}
	return 0
}

func (m *Reference) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Reference) GetInline() []byte {
	if m != nil {
		return m.Inline
	}
	return nil
}

func init() {
	proto.RegisterType((*Block)(nil), "structs.Block")
	proto.RegisterType((*Location)(nil), "structs.Location")
	proto.RegisterType((*Reference)(nil), "structs.Reference")
	proto.RegisterEnum("structs.BlockType", BlockType_name, BlockType_value)
}

func init() { proto.RegisterFile("structs.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 320 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x90, 0x5f, 0x6b, 0xb3, 0x30,
	0x14, 0x87, 0x5f, 0x6d, 0xec, 0xab, 0x67, 0x5a, 0xb6, 0x5c, 0x0c, 0xe9, 0x95, 0x78, 0x31, 0x64,
	0x30, 0x0b, 0xdd, 0x27, 0xe8, 0x9f, 0x51, 0xba, 0xb9, 0x3a, 0x82, 0x0c, 0xb6, 0xbb, 0x54, 0xb3,
	0x36, 0xb4, 0x26, 0x62, 0xd3, 0x42, 0xd9, 0x97, 0x1f, 0x46, 0xbb, 0xab, 0x5d, 0x85, 0xe7, 0x77,
	0x72, 0x9e, 0x9c, 0x13, 0xf0, 0x0e, 0xaa, 0x3e, 0xe6, 0xea, 0x10, 0x57, 0xb5, 0x54, 0x12, 0xff,
	0xef, 0x70, 0x18, 0x6e, 0xb8, 0xda, 0x1e, 0xd7, 0x71, 0x2e, 0xcb, 0x11, 0xaf, 0x76, 0x9b, 0xd1,
	0x46, 0x3e, 0xe4, 0x5b, 0x59, 0x17, 0x23, 0xc1, 0x54, 0x7b, 0x39, 0x9c, 0x81, 0x35, 0xdd, 0xcb,
	0x7c, 0x87, 0xef, 0x00, 0x65, 0xe7, 0x8a, 0xf9, 0x46, 0x60, 0x44, 0x83, 0x31, 0x8e, 0x2f, 0x4e,
	0x5d, 0x6d, 0x2a, 0x04, 0xa9, 0x73, 0xc5, 0x30, 0x06, 0x34, 0xa7, 0x8a, 0xfa, 0x66, 0x60, 0x44,
	0x2e, 0x41, 0x05, 0x55, 0x34, 0xfc, 0x04, 0x3b, 0x91, 0x39, 0x55, 0x5c, 0x0a, 0x3c, 0x00, 0x73,
	0x59, 0x68, 0x8b, 0x4b, 0x4c, 0x5e, 0xe0, 0x21, 0xd8, 0x6f, 0x35, 0x97, 0x35, 0x57, 0x67, 0xdd,
	0x63, 0x11, 0xbb, 0xea, 0x18, 0x87, 0x60, 0xbd, 0x0b, 0x59, 0x30, 0xbf, 0x17, 0x18, 0xd1, 0xd5,
	0xd8, 0x8d, 0xf5, 0x74, 0xb1, 0xce, 0x88, 0x75, 0x6a, 0x8e, 0xf0, 0x1b, 0x1c, 0xc2, 0xbe, 0x58,
	0xcd, 0x44, 0xce, 0x5a, 0x19, 0x3b, 0x71, 0x79, 0x3c, 0x74, 0x4f, 0xd8, 0x55, 0xc7, 0x7f, 0x0d,
	0xd6, 0x64, 0xaf, 0x17, 0xbf, 0x47, 0x50, 0x29, 0x0b, 0xbd, 0xc0, 0x8a, 0x96, 0xcc, 0x47, 0x81,
	0x11, 0x39, 0x04, 0x09, 0x5a, 0x32, 0x7c, 0x0b, 0xfd, 0xa5, 0xd8, 0x73, 0xc1, 0x7c, 0x4b, 0x77,
	0xf7, 0xb9, 0xa6, 0xfb, 0x67, 0x70, 0x7e, 0xf7, 0xc7, 0x1e, 0x38, 0x24, 0x4d, 0xb3, 0x69, 0x92,
	0xce, 0x5e, 0xae, 0xff, 0x35, 0x38, 0x9f, 0x64, 0x93, 0x16, 0x0d, 0xec, 0x82, 0x9d, 0xa4, 0x8b,
	0x96, 0x4c, 0x7c, 0x03, 0x5e, 0x92, 0x2e, 0x9e, 0x56, 0x19, 0xf9, 0x68, 0xa3, 0xde, 0xba, 0xaf,
	0x3f, 0xfc, 0xf1, 0x27, 0x00, 0x00, 0xff, 0xff, 0xc3, 0x08, 0xcd, 0x24, 0xae, 0x01, 0x00, 0x00,
}
